version: '2.3'

services:

  express:
    image: node:14
    user: "node"
    working_dir: /usr/src/app
    environment:
      NODE_ENV: "development"
    
    volumes:
      - ./:/usr/src/app
    ports:
      - "9200:9200"
      - "3035:1337"
    expose:
      - "1337"
    entrypoint: "npm run webpack"

networks:
  default:
    external:
      name: aha_hockey